[package]
name = "sp1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives = "0.6.2"
alloy-dyn-abi = "0.6.2"
rlp = "0.4.6"
